I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 132, in script
    python:
  File "game/script.rpy", line 139, in <module>
    if w<0 or h<0:
NameError: name 'w' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 132, in script
    python:
  File "C:\Users\ferro\Desktop\SI UMN\VN Code\renpy-7.4.10-sdk/renpy/ast.py", line 928, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\ferro\Desktop\SI UMN\VN Code\renpy-7.4.10-sdk/renpy/python.py", line 2245, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 139, in <module>
    if w<0 or h<0:
NameError: name 'w' is not defined

Windows-10-10.0.19041
Ren'Py 7.4.11.2266
koor_prep 1.0
Wed Jul  6 22:15:30 2022
